@startuml
class PostalAddress {
    + Address1 : string <<get>> <<set>>
    + Address2 : string <<get>> <<set>>
    + City : string <<get>> <<set>>
    + State : string <<get>> <<set>>
    + Zip : string <<get>> <<set>>
}
@enduml
