# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # Check for missing plugins
	unless Vagrant.has_plugin?("vagrant-disksize")
	    system "vagrant plugin install vagrant-disksize"
		exec "vagrant #{ARGV.join(' ')}"
	end

    config.vm.box = "ubuntu/disco64"
	config.disksize.size = '40GB'
    config.vm.provision "shell", path: "provision/node.sh", privileged: true
    config.vm.synced_folder "./workspace", "/home/vagrant/workspace", :create => true

    # Managers
    (1..3).each do |number|
        config.vm.define "m#{number}" do |node|
            node.vm.network "private_network", ip: "192.168.99.20#{number}"
            node.vm.hostname = "m#{number}"
        end  
    end

    # Workers
    (1..4).each do |number|
        config.vm.define "w#{number}" do |node|
            node.vm.network "private_network", ip: "192.168.99.21#{number}"
            node.vm.hostname = "w#{number}"
        end  
    end

    config.vm.provider "virtualbox" do |v|
        v.memory = 2048 
        v.cpus = 2
    end

end